image: archlinux
packages:
  - hugo
sources:
  - https://git.sr.ht/~alanorth/picturingjordan.com
tasks:
  - build: |
      id
      hugo version
      cd picturingjordan.com
      git clone --depth 1 https://git.sr.ht/~alanorth/hugo-theme-bootstrap4-blog themes/hugo-theme-bootstrap4-blog
      hugo
