language: go
go:
  - "1.15.x"
env:
  global:
    - CACHE_NAME=${TRAVIS_ARCH}
    - GOPROXY=https://proxy.golang.org
install:
  - mkdir -p $HOME/src
  - git clone https://github.com/gohugoio/hugo.git $HOME/src/hugo
  - cd $HOME/src/hugo
  - go install
before_script:
  - cd $TRAVIS_HOME/gopath/src/github.com/alanorth/picturingjordan.com
  - git clone https://github.com/alanorth/hugo-theme-bootstrap4-blog.git themes/hugo-theme-bootstrap4-blog
script:
  - hugo
os: linux
arch: arm64-graviton2
dist: focal

# vim: ts=2 sw=2 et
