language: go
go:
  - "1.15.x"
install:
  - mkdir -p $HOME/src
  - git clone https://github.com/gohugoio/hugo.git $HOME/src/hugo
  - cd $HOME/src/hugo
  - go install
before_script:
  - cd $TRAVIS_HOME/gopath/src/github.com/alanorth/picturingjordan.com
  - git clone https://github.com/alanorth/hugo-theme-bootstrap4-blog.git themes/hugo-theme-bootstrap4-blog
script:
  - hugo
dist: bionic

# vim: ts=2 sw=2 et
