# Hugo variables
# 
baseurl = "https://picturingjordan.com/"
languageCode = "en-us"
title = "Picturing Jordan"
theme = "hugo-theme-bootstrap4-blog"
enableRobotsTXT = true
# number of posts to show on home/category/tag pages (Default: 10)
paginate = 3
copyright = "Except where otherwise noted, content on this site is licensed under a <a rel='license' href='https://creativecommons.org/licenses/by-sa/4.0/'>Creative Commons Attribution 4.0 International license</a>."
enableGitInfo = true

[permalinks]
  posts = "/:year/:month/:slug/"
  page = "/:slug/"

[params]
  # Site author
  author = "Alan Orth"

  # Description/subtitle for homepage (can be Markdown)
  description = "Sharing Jordan with the world — one picture at a time."

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # verification string for Google Webmaster Tools
  google_verify_meta = "BAi69DROASu2b2mkVNA_EyUsobfH7Mq8BmSg2Rn-Zp4"

  # verification string for Bing Webmaster Tools
  bing_verify_meta = "2CA373095D945D1AA256B1CD8A3DF872"

  # verification string for Yandex Webmaster Tools
  yandex_verify_meta = "96b099438f75a04a"

  # show sharing icons on pages/posts (default: true)
  #sharingicons = true

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    about = "*Picturing Jordan*, sharing Jordan with the world — one picture at a time.<br><br>[Read more →](/about)"

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 2

  [params.social]
    # twitter handle for the site (ideally not a person, eg: nytimes, flickr, etc)
    twitter = "picturingjordan"

[[menu.sidebar]]
  name = "Alan in Kenya"
  url = "https://alaninkenya.org"

[[menu.sidebar]]
  name = "Mjanja Tech"
  url = "https://mjanja.ch"

[[menu.sidebar]]
  name = "English Bulgaria"
  url = "https://englishbulgaria.net"

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
DefaultContentLanguage = "en"

# Languages to render
[languages.en]
[languages.bg]
  date_format = "02 Jan 2006"
[languages.ar]
[languages.fa]

# vim: ts=2 sw=2 et
